# Computation, Problem Set #1b, Python Intro

### 1. Exercises from ACME: Intro to NumPy

#### 1.1

In [38]:
import numpy as np

# 1.1

A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])

A, B, A @ B

[[ 3 -1  4]
 [ 1  5 -9]] [[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3 -2 -3]] [[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [6]:
# 1.2

A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])

A, -(A @ A @ A) + 9 * (A @ A) - 15 * A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
# 1.3

A = np.triu(np.ones(7))
B = np.triu(np.ones(7) * 5, 1) + np.tril(np.ones(7) * (-1))

C = A @ B @ A

A, B, C.astype(np.int64)

(array([[1., 1., 1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1.]]),
 array([[-1.,  5.,  5.,  5.,  5.,  5.,  5.],
        [-1., -1.,  5.,  5.,  5.,  5.,  5.],
        [-1., -1., -1.,  5.,  5.,  5.,  5.],
        [-1., -1., -1., -1.,  5.,  5.,  5.],
        [-1., -1., -1., -1., -1.,  5.,  5.],
        [-1., -1., -1., -1., -1., -1.,  5.],
        [-1., -1., -1., -1., -1., -1., -1.]]),
 array([[ -7,  -8,  -3,   8,  25,  48,  77],
        [ -6, -12, -12,  -6,   6,  24,  48],
        [ -5, -10, -15, -14,  -7,   6,  25],
        [ -4,  -8, -12, -16, -14,  -6,   8],
        [ -3,  -6,  -9, -12, -15, -12,  -3],
        [ -2,  -4,  -6,  -8, -10, -12,  -8],
        [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64))

In [15]:
# 1.4


def positive_copy(x):

    res = x.copy()

    res[x < 0] = 0

    return res


positive_copy(B)

array([[0., 5., 5., 5., 5., 5., 5.],
       [0., 0., 5., 5., 5., 5., 5.],
       [0., 0., 0., 5., 5., 5., 5.],
       [0., 0., 0., 0., 5., 5., 5.],
       [0., 0., 0., 0., 0., 5., 5.],
       [0., 0., 0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
# 1.5

A = np.arange(6).reshape((3, 2)).T
B = np.tril(np.ones(3) * 3)
C = np.eye(3) * (-2)

A, B, C

(array([[0, 2, 4],
        [1, 3, 5]]), array([[3., 0., 0.],
        [3., 3., 0.],
        [3., 3., 3.]]), array([[-2., -0., -0.],
        [-0., -2., -0.],
        [-0., -0., -2.]]))

In [37]:
np.hstack(
    np.vstack((np.zeros(3), A, B)),
    np.vstack((A.T, np.zeros_like(A), np.zeros_like(B))),
    np.vstack((np.eye(3), np.zeros_like(C), C)),
)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [31]:
A = np.arange(6).reshape((2, 3))
B = np.zeros((4, 3))
# vstack() stacks arrays vertically (row-wise).
A, B, np.vstack((A, B, A))

(array([[0, 1, 2],
        [3, 4, 5]]), array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), array([[0., 1., 2.],
        [3., 4., 5.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 2.],
        [3., 4., 5.]]))

In [34]:
A = A.T
B = np.ones((3, 4))
# hstack() stacks arrays horizontally (column-wise).
A, B, np.hstack((A, B, A))

(array([[0, 3],
        [1, 4],
        [2, 5]]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[0., 3., 1., 1., 1., 1., 0., 3.],
        [1., 4., 1., 1., 1., 1., 1., 4.],
        [2., 5., 1., 1., 1., 1., 2., 5.]]))

In [28]:
# column_stack() stacks arrays horizontally, including 1-D arrays.
np.column_stack((A, np.zeros(3), np.ones(3), np.full(3, 2)))

array([[0., 3., 0., 1., 2.],
       [1., 4., 0., 1., 2.],
       [2., 5., 0., 1., 2.]])

In [ ]:
# 1.6


def row_stochastic(x):
    return x / np.sum(x, axis=0)

In [39]:
A

array([[ 3, -1,  4],
       [ 1,  5, -9]])

In [42]:
A / np.sum(A, axis=1)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [43]:
# 1.7

grid = np.load("grid.npy")

array([[ 8,  2, 22, 97, 38, 15,  0, 40,  0, 75,  4,  5,  7, 78, 52, 12,
        50, 77, 91,  8],
       [49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48,
         4, 56, 62,  0],
       [81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30,  3,
        49, 13, 36, 65],
       [52, 70, 95, 23,  4, 60, 11, 42, 69, 24, 68, 56,  1, 32, 56, 71,
        37,  2, 36, 91],
       [22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28,
        66, 33, 13, 80],
       [24, 47, 32, 60, 99,  3, 45,  2, 44, 75, 33, 53, 78, 36, 84, 20,
        35, 17, 12, 50],
       [32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66,
        18, 38, 64, 70],
       [67, 26, 20, 68,  2, 62, 12, 20, 95, 63, 94, 39, 63,  8, 40, 91,
        66, 49, 94, 21],
       [24, 55, 58,  5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88,
        34, 89, 63, 72],
       [21, 36, 23,  9, 75,  0, 76, 44, 20, 45, 35, 14,  0, 61, 33, 97,
        34, 31, 33, 95],
       [78, 17, 53, 28, 22, 75